### ISSUE TITLE
Logging function

### ISSUE THREAD

**Issue by DevOnWheels** [sharafc/php-explorer-blog#1]
Write a logging function which 

- accepts three parameters: `$message` (_required_), `$priority` (_optional_, default "error"), `$mode` (_optional_, default "")
- can have three logging modi: screen, file, database. A combination of multiple modi must be possible!
- should add date/time and location (which file/line) to your message

The function should accept a global logging mode, which can be overwritten be the optional parameter `$mode`. If you have the screen mode active, the output format is up to you, be creative ;-) If the database mode is active, split your logging information into logical columns like message, priority and so on.

Hint: priority and mode values don't have to be strings, obviously :-)

NO, DON'T USE `error_log()` (or any other build-in logging method for that matter) OR A LIBRARY LIKE MONOLOG! :D

**Comment by sharafc** [comment]
See: https://gist.github.com/sharafc/2dcf7a6aa05d77c900b5f14b0df77945
Will be added when I am finished with Router and Session Handler.
